version: "3"

services:
  omeroserver:
    ports:
      - "4064:4064"
  omeroweb:
    build: .
    image: custom-omero-web:prod
    ports:
      - "4080:4080"
    volumes:
      - ./config/02-additional-config.omero:/opt/omero/web/config/02-additional-config.omero:ro

  web:
    image: nginx:1
    networks:
      - omero
    ports:
      - "8443:443"
    volumes:
      - ./config/omeroweb.conf:/etc/nginx/conf.d/omeroweb.conf:ro
      - ./keys/localhost.crt:/opt/self.crt:ro
      - ./keys/localhost.key:/opt/self.key:ro