version: "3"

services:
  omeroserver:
    ports:
      - "4063:4063"
      - "4064:4064"
  omeroweb:
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: custom-omero-web:debug
    ports:
      - "4080:4080"
      - "8443:443"
