services:
  database:
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: $OMERO_DB_PASSWORD
  omeroserver:
    restart: unless-stopped
    environment:
      CONFIG_omero_db_pass: $OMERO_DB_PASSWORD
      CONFIG_omero_sessions_timeout: 7200000 # 2h in ms
      CONFIG_omero_db_poolsize: 100
      # CONFIG_omero_jvmcfg_percent_pixeldata: 30 # use 30% of memory for pixeldata
      # CONFIG_omero_jvmcfg_percent_blitz: 30 # use 30% of memory for blitz server
      ROOTPASS: $OMERO_ROOT_PASSWORD
  omeroweb:
    restart: unless-stopped
    build: .
    image: custom-omero-web:prod
    environment:
      #CONFIG_web_wsgi__workers: 5 # (2 x NUM_CORES) + 1
      CONFIG_omero_web_csrf__trusted__origins: $OMERO_TRUSTED_ORIGINS
    volumes:
      - ./config/02-additional-config.omero:/opt/omero/web/config/02-additional-config.omero:ro
    ports:
      - "4080:4080"
