version: "3"

services:
  database:
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: $OMERO_DB_PASSWORD
  omeroserver:
    restart: unless-stopped
    environment:
      CONFIG_omero_db_pass: $OMERO_DB_PASSWORD
      ROOTPASS: $OMERO_ROOT_PASSWORD
  omeroweb:
    restart: unless-stopped
    build: .
    image: custom-omero-web:prod
    volumes:
      - ./config/02-additional-config.omero:/opt/omero/web/config/02-additional-config.omero:ro
    ports:
      - "4080:4080"
